8.x 1.x hook2event
Capgemini/spalp pull request #1
Opened 2018-08-27 19:18 UTC by shashikant-walkunde-cg

Convert the current hook_spalp_app_ids_alter implementation with event dispatcher and subscriber approach for sub-modules to provide their app id 

Reference Issue - https://www.drupal.org/project/spalp/issues/2993774

2018-08-27 19:24 UTC, aaronferris commented on spalp.module
> +  // reset app ids
Reset

2018-08-27 19:24 UTC, aaronferris commented on spalp.module
> +  // return updated ids from event
Return

2018-08-27 19:24 UTC, aaronferris commented on spalp_example/src/EventSubscriber/SpalpExampleAppIdsAlterSubscriber.php
> +class SpalpExampleAppIdsAlterSubscriber implements EventSubscriberInterface {
The indentation in this file needs tidying up

2018-08-28 13:01 UTC, malcomio requested changes

2018-08-28 13:01 UTC, malcomio commented on spalp.module
> +function spalp_get_app_ids(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
please could you set up your IDE to follow Drupal coding standards: https://www.drupal.org/docs/develop/development-tools

2018-08-28 13:01 UTC, malcomio commented on spalp_example/spalp_example.module
> +define("SPALP_EXAMPLE_APP_ID", "spalp_example");
please use single quotes unless we need double quotes: https://www.drupal.org/docs/develop/standards/coding-standards#quotes

2018-08-28 13:01 UTC, malcomio commented on spalp_example/spalp_example.module
> -use Drupal\Core\Routing\RouteMatchInterface;
why delete this line? it's still being used in `spalp_example_help`

2018-08-28 13:15 UTC, aaronferris commented on spalp.module
> +
Remove one of these links

2018-08-28 13:15 UTC, aaronferris commented on spalp.module
Any reason why the 'use' below is separated out from the ones above?

2018-08-28 13:15 UTC, aaronferris commented on spalp.module
> +  // Reset app ids
Full stop

2018-08-28 13:15 UTC, aaronferris commented on spalp.module
> +  // Return updated ids from event
Full stop

2018-08-28 14:04 UTC, dakkusingh reviewed
Please pay attention to coding standards.
```
 ~/Docker/drupal/web/modules/contrib/spalp   8.x-1.x-hook2event  phpcs --standard=DrupalPractice --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md .

FILE: ...g/web/modules/contrib/spalp/spalp_example/spalp_example.info.yml
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 6 | WARNING | All dependencies must be prefixed with the project
   |         | name, for example "drupal:"
----------------------------------------------------------------------


FILE: ...drupal/web/modules/contrib/spalp/spalp_example/spalp_example.module
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 8 | WARNING | Global constants should not be used, move it to a
   |         | class or interface
----------------------------------------------------------------------

Time: 86ms; Memory: 4Mb

 ~/Docker/drupal/web/modules/contrib/spalp   8.x-1.x-hook2event  phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md .

FILE: /Users/dakku/Docker/drupal/web/modules/contrib/spalp/README.md
----------------------------------------------------------------------
FOUND 0 ERRORS AND 4 WARNINGS AFFECTING 4 LINES
----------------------------------------------------------------------
  3 | WARNING | Line exceeds 80 characters; contains 119 characters
  5 | WARNING | Line exceeds 80 characters; contains 113 characters
 11 | WARNING | Line exceeds 80 characters; contains 105 characters
 21 | WARNING | Line exceeds 80 characters; contains 83 characters
----------------------------------------------------------------------


FILE: /Users/dakku/Docker/drupal/web/modules/contrib/spalp/spalp.api.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 18 | ERROR | [ ] Type hint "array" missing for $ids
 20 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, colons, question marks, or closing
    |       |     parentheses
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: /Users/dakku/Docker/drupal/web/modules/contrib/spalp/spalp.module
----------------------------------------------------------------------
FOUND 8 ERRORS AND 1 WARNING AFFECTING 9 LINES
----------------------------------------------------------------------
 12 | ERROR   | [x] There must be one blank line after the last USE
    |         |     statement; 2 found;
 18 | ERROR   | [x] Expected 1 blank line before function; 2 found
 39 | WARNING | [x] A comma should follow the last multiline array
    |         |     item. Found: ]
 56 | ERROR   | [x] Additional blank lines found at end of doc
    |         |     comment
 57 | ERROR   | [x] Whitespace found at end of line
 58 | ERROR   | [x] Inline comments must end in full-stops,
    |         |     exclamation marks, colons, question marks, or
    |         |     closing parentheses
 60 | ERROR   | [x] Whitespace found at end of line
 65 | ERROR   | [x] Whitespace found at end of line
 66 | ERROR   | [x] Inline comments must end in full-stops,
    |         |     exclamation marks, colons, question marks, or
    |         |     closing parentheses
----------------------------------------------------------------------
PHPCBF CAN FIX THE 9 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: ...xample/src/EventSubscriber/SpalpExampleAppIdsAlterSubscriber.php
----------------------------------------------------------------------
FOUND 3 ERRORS AND 1 WARNING AFFECTING 4 LINES
----------------------------------------------------------------------
  1 | ERROR   | [x] The PHP open tag must be followed by exactly one
    |         |     blank line
 16 | ERROR   | [x] Doc comment short description must be on the
    |         |     first line
 20 | WARNING | [x] A comma should follow the last multiline array
    |         |     item. Found: 'doAppIdsListAlter'
 27 | ERROR   | [ ] Missing parameter comment
----------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: ...al/web/modules/contrib/spalp/src/Event/SpalpAppIdsAlterEvent.php
----------------------------------------------------------------------
FOUND 8 ERRORS AFFECTING 5 LINES
----------------------------------------------------------------------
  8 | ERROR | [x] Doc comment short description must end with a full
    |       |     stop
 15 | ERROR | [x] Doc comment short description must end with a full
    |       |     stop
 16 | ERROR | [ ] Missing @var tag in member variable comment
 20 | ERROR | [x] Doc comment short description must end with a full
    |       |     stop
 22 | ERROR | [x] There should be no white space after an opening "("
 22 | ERROR | [x] Expected 0 spaces between opening bracket and
    |       |     argument "$ids"; 1 found
 22 | ERROR | [x] There should be no white space before a closing ")"
 22 | ERROR | [x] Expected 0 spaces between argument "$ids" and
    |       |     closing bracket; 1 found
----------------------------------------------------------------------
PHPCBF CAN FIX THE 7 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

Time: 727ms; Memory: 6Mb
```

2018-08-28 14:13 UTC, dakkusingh requested changes

2018-08-28 14:13 UTC, dakkusingh commented on spalp.api.php
>  function hook_spalp_app_ids_alter(&$ids) {
if the purpose of this PR is to transform hooks to events, then this hook doenst need to be here.

2018-08-28 14:37 UTC, dakkusingh commented on spalp_example/src/EventSubscriber/SpalpExampleAppIdsAlterSubscriber.php
> +    $event->ids[SPALP_EXAMPLE_APP_ID] = SPALP_EXAMPLE_APP_ID;
try to get in the habit of using getters and setters.. 

see examples below

**Event Getter / Setter:** 
https://github.com/nodespark/elasticsearch_connector/blob/8.x-5.x/src/Event/BuildSearchParamsEvent.php#L35

https://github.com/nodespark/elasticsearch_connector/blob/8.x-5.x/src/Event/BuildSearchParamsEvent.php#L44

**Subscriber Getter / Setter:** 
https://github.com/dakkusingh/search_api_elasticsearch_attachments/blob/8.x-1.x/src/EventSubscriber/BuildSearchParams.php#L30

https://github.com/dakkusingh/search_api_elasticsearch_attachments/blob/8.x-1.x/src/EventSubscriber/BuildSearchParams.php#L51

2018-08-28 14:41 UTC, dakkusingh commented on spalp_example/src/EventSubscriber/SpalpExampleAppIdsAlterSubscriber.php
> +    return [
try to improve readability of your code. Consider formatting it as shown in the example below:
https://github.com/dakkusingh/search_api_elasticsearch_attachments/blob/8.x-1.x/src/EventSubscriber/BuildSearchParams.php#L19

2018-08-28 14:42 UTC, dakkusingh commented on src/Event/SpalpAppIdsAlterEvent.php
> +   */
Param(s) are missing, see example:
https://github.com/nodespark/elasticsearch_connector/blob/8.x-5.x/src/Event/BuildSearchParamsEvent.php#L22

2018-08-28 14:43 UTC, dakkusingh commented on src/Event/SpalpAppIdsAlterEvent.php
> +}
try to get in the habit of using getters and setters..

see examples below

Event Getter / Setter:
https://github.com/nodespark/elasticsearch_connector/blob/8.x-5.x/src/Event/BuildSearchParamsEvent.php#L35

https://github.com/nodespark/elasticsearch_connector/blob/8.x-5.x/src/Event/BuildSearchParamsEvent.php#L44

2018-08-28 14:46 UTC, dakkusingh commented on spalp_example/spalp_example.services.yml
> +      - { name: 'event_subscriber' }
Check if single quote around `'event_subscriber'` is required?

2018-08-28 14:48 UTC, dakkusingh commented on spalp_example/src/EventSubscriber/SpalpExampleAppIdsAlterSubscriber.php
> +   * {@inheritdoc}
Missing @var tag in member variable comment

2018-08-28 14:57 UTC, dakkusingh commented on spalp.module
> +function spalp_get_app_ids(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
Consider making this into a service and not a function in a module file.
`function spalp_get_app_ids`

see (LOGIC) section in:
https://www.drupal.org/project/spalp/issues/2993322

2018-08-28 15:24 UTC, dakkusingh commented on spalp.module
> +  $event = new SpalpAppIdsAlterEvent($ids);
instead of functions in a module, consider making this into a service as discussed here: https://www.drupal.org/project/spalp/issues/2993322. 

See example using event dispatcher in services:
https://cgit.drupalcode.org/okta_api/tree/src/Service/Users.php?h=8.x-3.x#n120

2018-09-03 06:26 UTC, malcomio commented
replaced by #5

2018-09-03 06:26 UTC, closed without merging